services:
  db:
    image: postgres:17.6
    container_name: subscription_killer_db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=subscription_killer_db"
      - "POSTGRES_USER=guest"
      - "POSTGRES_PASSWORD=hello_guest"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server.crt:/var/lib/postgresql/server.crt:ro
      - ./server.key:/var/lib/postgresql/server.key:ro
    # Using a shell script to fix permissions at runtime
    entrypoint: >
      sh -c "
      cp /var/lib/postgresql/server.key /tmp/server.key &&
      chown postgres:postgres /tmp/server.key &&
      chmod 600 /tmp/server.key &&
      exec docker-entrypoint.sh postgres 
      -c ssl=on 
      -c ssl_cert_file=/var/lib/postgresql/server.crt 
      -c ssl_key_file=/tmp/server.key
      "

  elasticsearch:
    profiles: [ "observe" ]
    image: ghcr.io/openzipkin/zipkin-elasticsearch8:latest
    container_name: elasticsearch
    # Bind Mount: Survives 'docker compose down -v'
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 5
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  zipkin:
    profiles: [ "observe" ]
    image: openzipkin/zipkin:latest
    container_name: zipkin
    depends_on:
      - elasticsearch
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200

  grafana:
    profiles: [ "report" ]
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - zipkin

volumes:
  pgdata:
  grafana_data: