spring:
  config:
    activate:
      on-profile: local-ssl
server.port: 8443
server.ssl.key-store: classpath:certs/keystore.p12
server.ssl.key-store-password: password
server.ssl.key-store-type: PKCS12
server.ssl.key-alias: springboot