spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: subscription-killer-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_ENDPOINT}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${APP_GOOGLE_CLIENT_ID}
            client-secret: ${APP_GOOGLE_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            scope:
              - openid
              - email
              - profile
              - https://www.googleapis.com/auth/gmail.readonly
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent%20select_account
server:
  forward-headers-strategy: framework
app:
  oauth2:
    redirect-uri: http://localhost:3000/dashboard
  cors:
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    max-age: 3600
  mail:
    analysis-months: 13
  prompts:
    filter-and-categorize-emails: classpath:/prompts/eventRuleUpdate/1-filter-and-categorize-emails.st
    generalize-string-pattern: classpath:/prompts/eventRuleUpdate/2-generalize-string-pattern.st
    merge-email-detection-rules: classpath:/prompts/eventRuleUpdate/3-merge-event-rules.st
---
spring:
  config:
    activate:
      on-profile: gcp
  ai:
    google:
      genai:
        project-id: ${GOOGLE_CLOUD_PROJECT}
        api-key: ${SPRING_AI_GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.1
    chat:
      observations:
        log-prompt: true
        log-completion: true
app:
  google:
    client-id: ${APP_GOOGLE_CLIENT_ID}
    client-secret: ${APP_GOOGLE_CLIENT_SECRET}
---
spring:
  config:
    activate:
      on-profile: dev
app:
  cors:
    allowed-origins:
      - https://subscription-killer-git-main-matchalab-project.vercel.app
      - https://subscription-killer-git-staging-matchalab-project.vercel.app
      - https://localhost:3000
  mail:
    analysis-months: 8
logging:
  level:
    com.matchalab.subscription_killer_api: DEBUG
    org:
      springframework:
        ai: DEBUG
        security: DEBUG
    #        web.reactive.function.client.ExchangeFunctions: DEBUG
    web.filter: DEBUG
#    reactor.netty.http.client.HttpClient: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
app:
  cors:
    allowed-origins:
      - https://subscription-killer-git-main-matchalab-project.vercel.app