spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: subscription-killer-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_ENDPOINT}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${APP_GOOGLE_CLIENT_ID}
            client-secret: ${APP_GOOGLE_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            scope:
              - openid
              - email
              - profile
              - https://www.googleapis.com/auth/gmail.readonly
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent%20select_account
  session:
    jdbc:
      initialize-schema: always
    timeout: 3d
  autoconfigure:
    exclude:
      - org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration
server:
  forward-headers-strategy: framework
app:
  oauth2:
    redirect-uri: http://localhost:3000/report
  cors:
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    max-age: 3600
  mail:
    analysis-months: 13
  #  min-request-interval-hours: 72
  min-request-interval-hours: 0
  prompts:
    filter-and-categorize-emails: classpath:/prompts/eventRuleUpdate/active/1-filter-and-categorize-emails-v2.st
    generalize-string-pattern: classpath:/prompts/eventRuleUpdate/active/2-generalize-string-pattern-v3.st
logging:
  charset:
    console: UTF-8
---
spring:
  config:
    activate:
      on-profile: gcp
app:
  google:
    client-id: ${APP_GOOGLE_CLIENT_ID}
    client-secret: ${APP_GOOGLE_CLIENT_SECRET}
    token-server-url: https://oauth2.googleapis.com/token
    token-refresh-threshold-seconds: 300
---
spring:
  config:
    activate:
      on-profile: ai
  ai:
    retry:
      max-attempts: 1
    google:
      genai:
        project-id: ${GOOGLE_CLOUD_PROJECT}
        api-key: ${SPRING_AI_GOOGLE_GENAI_API_KEY_DEV}
        chat:
          options:
            model: gemini-3-flash-preview
            temperature: 0.1
            thinking-level: LOW
    #            thinking-budget: 0
    chat:
      observations:
        log-prompt: false
        log-completion: false
---
spring:
  config:
    activate:
      on-profile: dev
  reactor:
    context-propagation: auto
app:
  cors:
    allowed-origins:
      - https://subscription-killer-git-main-matchalab-project.vercel.app
      - https://subscription-killer-git-staging-matchalab-project.vercel.app
      - https://localhost:3000
      - http://localhost:3000
  mail:
    analysis-months: 8
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %-5line --- [%thread] %-40.40logger{39} : %msg%n"
  level:
    com.matchalab.subscription_killer_api: DEBUG
    org:
      springframework:
        #        ai: DEBUG
        security: DEBUG
        security.oauth2: DEBUG
        security.oauth2.client: DEBUG
        session: DEBUG
      hibernate:
        SQL: DEBUG
#        type.descriptor.sql.BasicBinder: TRACE
#    web.filter: DEBUG
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  info:
    git:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
app:
  cors:
    allowed-origins:
      - https://subscription-killer-git-main-matchalab-project.vercel.app