# https://docs.aws.amazon.com/ko_kr/lambda/latest/dg/deploying-github-actions.html

name: Deploy to AWS Lambda

env:
  AWS_REGION: ap-northeast-2

on:
  push:
    branches: [ "staging", "main" ]

permissions:
  id-token: write # This is required for OIDC authentication
  contents: read # This is required to checkout the repository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
          # The role-to-assume should be the ARN of the IAM role you created for GitHub Actions OIDC

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew test buildZip
        env:
          SPRING_PROFILES_ACTIVE: ci

      - name: Upload to S3
        run: |
          aws s3 cp build/distributions/*.zip s3://${{ vars.AWS_S3_BUCKET }}/subscription-killer-api.zip

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name ${{ vars.AWS_FUNCTION_NAME }} \
            --s3-bucket ${{ vars.AWS_S3_BUCKET }} \
            --s3-key subscription-killer-api.zip

#      - name: Deploy Lambda function via S3
#        uses: aws-actions/aws-lambda-deploy@v1.1.0
#        with:
#          function-name: ${{ vars.AWS_FUNCTION_NAME }}
#          code-artifacts-dir: build/distributions
#          s3-bucket: ${{ vars.AWS_S3_BUCKET }}
#          s3-key: subscription-killer-api.zip
